Repository navit-gps/navit, pull requests merged in 2018-04, with the labels that each got.

#429 maptool: migrate malloc/free/realloc to g_malloc/g_free/g_realloc
  navit/maptool/buffer.c
  navit/maptool/ch.c
  navit/maptool/google/protobuf-c/protobuf-c.c
  navit/maptool/maptool.c
  navit/maptool/misc.c
  navit/maptool/osm.c
  navit/maptool/osm_protobuf.c
  navit/maptool/osm_protobufdb.c
  navit/maptool/tile.c
  navit/maptool/zip.c
Labels: enhancement

#446 Github: Add a template for github issues
  .github/ISSUE_TEMPLATE.md
Labels: community

#447 Add:github: Add a contributing.md that references our wiki
  CONTRIBUTING.md
Labels: community

#453 Update:i18n:Updated French (fr) translation from launchpad
  po/fr.po.in
Labels: i18n
