Repository navit-gps/navit, pull requests merged in 2019-10, with the labels that each got.

#892 Prepare changelog for release 0.5.4
  CHANGELOG.md
Labels: doc

#916 update:docs:Migrate Android development documentation over
  docs/development/android_development.rst
  docs/index.rst
Labels: doc

#812 Add/Android Supporting sending & receiving geo: intents
  navit/android.c
  navit/android/AndroidManifest.xml
  navit/android/res/values/strings.xml
  navit/android/src/org/navitproject/navit/Navit.java
  navit/android/src/org/navitproject/navit/NavitGraphics.java
  navit/coord.h
Labels: android

#927 update:doc: Fix windows doc and cleanup sphinx warnings
  CHANGELOG.md
  docs/development/android_development.rst
  docs/development/wince_development.rst
  docs/development/windows_development.rst
Labels: cleanup, doc

#928 fix:core:Don't flood stack on big map elements
  navit/graphics.c
  navit/item.c
  navit/item.h
  navit/map/binfile/binfile.c
Labels: core

#932 Update:i18n:Updated Welsh translation from launchpad
  po/cy.po.in
Labels: i18n

#935 fix:all:fix compiler warnings
  navit/attr.c
  navit/attr.h
  navit/binding/dbus/binding_dbus.c
  navit/bookmarks.c
  navit/config_.c
  navit/config_.h
  navit/coord.c
  navit/debug.c
  navit/file.c
  navit/gui/gtk/gui_gtk_action.c
  navit/gui/gtk/gui_gtk_window.c
  navit/gui/internal/gui_internal_command.c
  navit/gui/qt5_qml/backend.cpp
  navit/layout.c
  navit/layout.h
  navit/log.c
  navit/main.c
  navit/mapset.c
  navit/mapset.h
  navit/maptool/maptool.c
  navit/navigation.c
  navit/navit.c
  navit/navit.h
  navit/plugin.c
  navit/plugin.h
  navit/popup.c
  navit/route.c
  navit/traffic.c
  navit/xmlconfig.c
  navit/xmlconfig.h
Labels: WIP, cleanup, core

#934 Update:i18n:Updated German (Switzerland) translation from launchpad
  po/de_CH.po.in
Labels: i18n

#929 cleanup:ci:Simplify the listing of files for sanity check
  scripts/ci_sanity_checks.sh
Labels: build system, cleanup

#933 Update:i18n:Updated Danish translation from launchpad
  po/da.po.in
Labels: i18n

#931 Update:i18n:Updated Kurdish (Sorani) translation from launchpad
  po/ckb.po.in
Labels: i18n
