Repository navit-gps/navit, pull requests merged in 2020-01, with the labels that each got.

#889 feature:graphics/android: add polygons with holes support
  navit/android/src/org/navitproject/navit/NavitGraphics.java
  navit/graphics/android/graphics_android.c
Labels: WIP, android

#959 vehicle:fix: add compatibility for gpsd 3.20
  navit/vehicle/gpsd/vehicle_gpsd.c
Labels: core

#971 Update:CI: Use debian:latest in the CI to get more up-to-date tools
  .circleci/config.yml
Labels: build system
